#!/usr/bin/env zsh
# Pi invokes shellPath as: <shellPath> -c <command>.
if [[ "$1" == "-c" ]]; then
    shift
    if [[ -r "$HOME/.oh-my-zsh/plugins/git/git.plugin.zsh" ]]; then
        compdef() { :; }
        source "$HOME/.oh-my-zsh/plugins/git/git.plugin.zsh" || exit 1
        unfunction compdef
    fi
    source "$HOME/.config/zsh/aliases.zsh" || exit 1
    eval "$1"
else
    exec "$(command -v zsh)" "$@"
fi
